# Generated by Django 5.1.3 on 2024-11-29 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('fabrication_cost', models.IntegerField()),
                ('spraying_cost', models.IntegerField()),
                ('costing_method', models.CharField(choices=[('PU', 'Per Unit'), ('BM', 'By Measurements')], max_length=5)),
                ('unit_name', models.CharField(blank=True, max_length=20, null=True)),
                ('min_height', models.FloatField(blank=True, null=True)),
                ('min_length', models.FloatField(blank=True, null=True)),
                ('max_height', models.FloatField(blank=True, null=True)),
                ('max_length', models.FloatField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabourCostings.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='LabourTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField()),
                ('item_costings', models.ManyToManyField(to='LabourCostings.itemcosting')),
            ],
        ),
    ]
