# Generated by Django 5.1.3 on 2024-12-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabourCostings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourtable',
            name='item_costings',
        ),
        migrations.AddField(
            model_name='itemcosting',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourCostings.labourtable'),
        ),
    ]
