# Generated by Django 5.1.3 on 2024-12-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabourCostings', '0002_remove_labourtable_item_costings_itemcosting_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcosting',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabourCostings.labourtable'),
        ),
    ]
