# Generated by Django 5.1.3 on 2024-12-16 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabourCostings', '0003_alter_itemcosting_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcosting',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcosting',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_costings', to='LabourCostings.labourtable'),
        ),
    ]
