# Generated by Django 5.1.3 on 2024-12-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabourCostings', '0005_alter_itemcosting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcosting',
            name='fabrication_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemcosting',
            name='spraying_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
