# Generated by Django 5.1.3 on 2024-12-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabourCostings', '0006_alter_itemcosting_fabrication_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcosting',
            name='fabrication_cost',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemcosting',
            name='spraying_cost',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemcosting',
            name='unit_name',
            field=models.CharField(choices=[('m', 'Meter'), ('cm', 'Centimeter'), ('mm', 'Millimeter'), ('sqm', 'Square Meter'), ('in', 'Inch'), ('ft', 'Feet')], max_length=20),
        ),
    ]
