# Generated by Django 4.2.7 on 2024-01-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dark_theme",
            field=models.BooleanField(default=False),
        ),
    ]
