# Generated by Django 4.2.7 on 2024-04-10 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuserpermissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuserpermissions",
            options={
                "permissions": [
                    ("is_head_technician", "Is Head Technician"),
                    ("can_view_profit", "Can View Profit"),
                ]
            },
        ),
    ]
