# Generated by Django 4.2.7 on 2024-09-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('accounts', '0004_alter_customuserpermissions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='files',
            field=models.ManyToManyField(blank=True, to='files.file'),
        ),
    ]
