# Generated by Django 4.2.7 on 2024-10-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_1",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
