/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2023-11-20 07:29:09 
*/
import { Checklist, Customer, Issue, JSONObject, JobCard, Receipt, Vehicle } from "../classes/classes";

export interface IjobCardForm {
    customers: Customer[];
    customers_matched: Customer[];
    vehicles: Vehicle[];
    vehicles_matched: Vehicle[];
    issues: any[];
    diagnostics: any[]
    update_state: boolean;
    add_customer_show: boolean;
    add_vehicle_show: boolean;
    customer_picker: boolean;
    vehicle_picker: boolean;
    show_customers: boolean
    show_vehicles: boolean
    load: boolean;
    issue_count: number;
    diagnostic_count: number
    customerSelected: any;
    vehicleSelected: any
    customerEdit: Customer;
    vehicleEdit: Vehicle
    checklist: Checklist
    jobcard: JobCard
    jobcard_types: Array<any>
    selected_jobcard_types: Array<any>
    conditions: Array<any>
    selected_conditions: Array<any>
    urls: any
    url: any
    closeForm(): any
    show_picker(index: number): any
    pickerSelect(object: Customer | Vehicle, index: number): any
    addTask(num: number): any
    removeTask(task: Issue, num: number): any
    handleSearch(event: Event, num: number): any
    requestSubmit(): any
    handleFormSubmit(event: Event): any
    getIssuesString(num: number): any
    handleCustomerSubmit(event: Event): Promise<void>
    handleVehicleSubmit(event: Event): Promise<void>
    generateTasks(text: string, num: number): any
    selectType(type: any): void
    selectCondition(condition: any): void
    normalInit(): Promise<void>
    overallInit(pk?: string | false): Promise<JSONObject>
    updateInit(pk: number, url: string): Promise<void>
    getObject(pk: number, obj: any[], num: number): any
    setDefaults(obj: any, num: number): any
}

export interface Iaccounts {
    add_mode: boolean,
    load: boolean,
    urls: any,
    accounts: any,
    receipts: any,
    getTotal(): number,
    requestSubmit(): void,
    init(): void
}
