# Generated by Django 5.1.3 on 2025-01-06 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0001_initial'),
        ('LabourCostings', '0007_alter_itemcosting_fabrication_cost_and_more'),
        ('Projects', '0003_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_groups', to='Projects.project')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabourCostings.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('height', models.FloatField()),
                ('length', models.FloatField()),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabourCostings.itemcosting')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
                ('item_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.itemgroup')),
            ],
        ),
    ]
