# Generated by Django 5.1.3 on 2025-01-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Items.itemgroup'),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
