# Generated by Django 5.1.3 on 2025-01-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_alter_item_height_alter_item_item_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
    ]
